### ISSUE TITLE
chore: release and publish task

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/zally-web-ui#11]
Ideally we should have a npm script that release and publish a new version with one command.

```sh
$ npm run release [major|minor|path]
```

Pre-review:

- [ ] git checkout to new branch `release/<next-version>`
- [ ] run tests
- [ ] bump package.json version
- [ ] build client assets 
- [ ] generate changelog
- [ ] git add changes 
- [ ] git commit changes
- [ ] git push changes
- [ ] manually open a PR against master (or also this step can be automated?)

After review:

- [ ] git add tag
- [ ] git push tag
- [ ] publish on npm

Ideally this task should run on a CI server but it should be possible to do that manually.

**Comment by EduardoAC** [comment]
Hi @rbarilani, I want to ask you about this issue in order to start working on it. 

I understand the concept of one command release. However the `pre-review` steps I am not familiar with this kind of release system.

- if you want to create a new release from master, shouldn't it be already upgraded it the `package.json` version already? 
- Why do you need the client assets on a PR? Couldn't you just generate then using `prepublishOnly` option?
- The content of the changelog need to be from the last release, Should I need to identify from the last tag or do you have another syste,?

I am a bit green on releasing this way, but it's a good exercise to come back to releases from CD

**Comment by rbarilani** [comment]
Hi @EduardoAC thx for looking into this.

> if you want to create a new release from master, shouldn't it be already upgraded it the package.json version already?

The release artifacts (changelog, bumped package.json, eventually compiled artifacts and so on) are produced on a specific release branch to be able to review before merging to master (at the point we really publish... add git tag and publish to npm)

> Why do you need the client assets on a PR? Couldn't you just generate then using prepublishOnly option?

We can remove that when we are stable enough but I find it beneficial when you wanna test a release candidate in another project without publishing on npm so you can use a git reference instead of a version.

> The content of the changelog need to be from the last release, Should I need to identify from the last tag or do you have another system?

I usually use this tool that do that for you: https://github.com/conventional-changelog/conventional-changelog


> I am a bit green on releasing this way, but it's a good exercise to come back to releases from CD

This process should be available as manual or and preferred run on CI/CD servers.

**Comment by rbarilani** [comment]
@EduardoAC BTW Those steps or procedures or approaches are not written in the stone so I'm really open to alternative proposal and discussions.

**Comment by maxim-tschumak** [comment]
Moved to https://github.com/zalando-incubator/zally/issues/462
